### PR TITLE
feature: option 'default layer'

### PR DESCRIPTION
**Pull request by gswly**
This PR allows the user to choose a default layer between the 3 already available.

deflayer

### CODE REVIEW

**Comment by pR0Ps** [comment]
In order to display the default map, you shouldn't need to remove and re-add everything. Just adding the default layer after adding the layer group should work.

Also, I haven't tested this, but if the `const layers` definition was pulled out of the `setupMap` function, it should be possible to access it from the preferences pane using something like `ng-options="f for f in ctrl.mapLayers"` right? That way the panels would only have to be updated in a single place if they're changed or renamed later.

**Comment by gswly** [comment]
Hi, i've updated the PR to solve the merge conflict and address your points.

> In order to display the default map, you shouldn't need to remove and re-add everything. Just adding the default layer after adding the layer group should work.

I tested this approach but it did not work: it is in fact necessary to remove all layers and add the default one to the map for the change to take effect immediately. Nonetheless i've simplified the update procedure.

> Also, I haven't tested this, but if the const layers definition was pulled out of the setupMap function, it should be possible to access it from the preferences pane using something like ng-options="f for f in ctrl.mapLayers" right? That way the panels would only have to be updated in a single place if they're changed or renamed later.

done

**Comment by pR0Ps** [comment]
@gswly I made a few tweaks to address some issues I saw while testing, but overall it worked perfectly. Thanks for the contribution!

**Comment by gswly** [comment]
thanks and keep up the good work

**Pull request merged**
